### PR TITLE
ISSUE-4 Basic File Management

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses https://github.com/capstone-coal/coal-sds/issues/4
All I did to produce this code was read the [OODT File Management User Guide](https://cwiki.apache.org/confluence/display/OODT/OODT+Filemgr+User+Guide).
With this PR, alongside the [documentation](https://github.com/capstone-coal/coal-sds/wiki/Basic-File-Management-in-COAL-SDS) provides the basis for the very basics of file management.
Lets discuss this, and I will demo when we have our next meeting.

### CODE REVIEW

**Comment by lewismc** [comment]
By the way, if you are interested in some trivial improvements I am proposing to make to OODT through this task, see https://github.com/apache/oodt/pull/56

**Comment by chrismattmann** [comment]
@lewismc i'll go ahead and commit this, looks good to me.

**Comment by chrismattmann** [comment]
also, note, much of the file:// etc, is obviated by _how_ environment variables for e.g., [FILEMGR_HOME] and etc., are defined. My suggestion is always for people to look at the DRAT wiki in this sense, which has good examples of what these should be set to.

**Comment by lewismc** [comment]
ACK @chrismattmann thank you for the resources. Much appreciated. We are still getting started over here so lots more to come.

**Pull request merged**
